import NavigationArrow from './NavigationArrow.svg';
import Setting from './Setting.svg';
import Location from './Location.svg';
import Rain from './Rain.svg';
import Cancel from './Cancel.svg';
import RegionItemDelete from './RegionItemDelete.svg';
import SortArrowDown from './SortArrowDown.svg';
import People from './People.svg';
import LocationPin from './LocationPin.svg';
import Warning from './Warning.svg';
import Map from './Map.svg';
import WildFire from './WildFire.svg';
import LandSlide from './Landslide.svg';
import Flood from './Flood.svg';
import Dust from './Dust.svg';
import Snow from './Snow.svg';
import BackArrow from './BackArrow.svg';
import Call from './Call.svg';
import Arrow from './Arrow.svg';
import Information from './Information.svg';
import Fire from './Fire.svg';
import MyPage from './MyPage.svg';
import BubbleTail from './BubbleTail.svg';
import AlertBell from './AlertBell.svg';
import DownArrow from './DownArrow.svg';
import TimeStepMarker from './TimeStepMarker.svg';
import Flame from './Flame.svg';

export { NavigationArrow };
export { Setting as SettingIcon };
export { Location as LocationIcon };
export { Rain as RainIcon };
export { Cancel as CancelIcon };
export { RegionItemDelete as RegionItemDeleteIcon };
export { SortArrowDown as SortArrowDownIcon };
export { People as PeopleIcon };
export { LocationPin as LocationPinIcon };
export { Warning as WarningIcon };
export { Map as MapIcon };
export { WildFire as WildFireIcon };
export { LandSlide as LandSlideIcon };
export { Flood as FloodIcon };
export { Dust as DustIcon };
export { Snow as SnowIcon };
export { BackArrow as BackArrowIcon };
export { Call as CallIcon };
export { Arrow as ArrowIcon };
export { Information as InformationIcon };
export { Fire as FireIcon };
export { MyPage as MyPageIcon };
export { BubbleTail };
export { AlertBell as AlertBellIcon };
export { DownArrow as DownArrowIcon };
export { TimeStepMarker };
export { Flame as FlameIcon };
